#!/bin/bash
#
#SBATCH --job-name=long-ext1
#SBATCH --output=long-ext.txt
#SBATCH --ntasks-per-node=40
#SBATCH --nodes=1
#SBATCH --time=7-00:00:00
#SBATCH -p extended-40core

module load shared
module load gcc/9.2.0

cd /gpfs/scratch/rperna/Neptune/code

./longterm ext1
